name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CARGO_INCREMENTAL: 0
  SCCACHE_GHA_VERSION: "sccache"
  SCCACHE_IDLE_TIMEOUT: 0
  SCCACHE_BYPASS_CHECK: "on"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rui314/setup-mold@v1
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ hashFiles('**/Cargo.lock') }}-${{ steps.toolchain.outputs.rustc_hash }}
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run sccache stat
        shell: bash
        run: ${SCCACHE_PATH} --show-stats
